### PR TITLE
Problem: metadata of dataset is missing

### LINKED ISSUE #23: Problem: S3 folders (prefixes) are not supported
The adapter will fail to download an object with an address like `s3://bucket-name/folder-a/bird-sounds.mp3` because it doesn't know yet that `folder-a` means to be a directory that needs to be pre-created.

### PR DESCRIPTION
**Pull request by sevein**
This PR updates the adapter so the metadata of the dataset is also included in `metadata.json` - the entry has the value `objects/` in the `filename` column.

Also, this issue closes #23 and I've enabled coveralls.io and added some extra badges to the README file.

--- 

These will be the badges shown once this PR is merged:

[Travis CI](https://travis-ci.org/JiscRDSS/rdss-archivematica-channel-adapter) [GoDoc](https://godoc.org/github.com/JiscRDSS/rdss-archivematica-channel-adapter) [Coverage Status](https://coveralls.io/github/JiscRDSS/rdss-archivematica-channel-adapter?branch=master) [Go Report Card](https://goreportcard.com/report/JiscRDSS/rdss-archivematica-channel-adapter) [Sourcegraph](https://sourcegraph.com/github.com/JiscRDSS/rdss-archivematica-channel-adapter?badge)

### CODE REVIEW

File: broker/backend/kinesis/processor_test.go [hunk 1]
```diff
@@ -71,6 +71,10 @@ func (d myKinesis) DescribeStream(input *kinesis.DescribeStreamInput) (*kinesis.
 	return output, nil
 }
 
+func (d myKinesis) DescribeStreamPages(*kinesis.DescribeStreamInput, func(*kinesis.DescribeStreamOutput, bool) bool) error {
+	return nil
+}
```
Comment (sevein) [inline broker/backend/kinesis/processor_test.go]: coveralls wouldn't work unless I implement this method which makes sense because it's used by the kinsumer library. I guess the compiler didn't complain until now because the code path I was targeting from my test wasn't as wide as the one done by the coveralls tool? I'm not sure...
